baseurl = ""
languageCode = "en-us"
title = "Vinay Hiremath"
theme = "hyde-x"
relativeurls = true

[author]
	name = "Vinay Hiremath"

[params]
	theme = "theme-base-09"
	tagline = "I'm especially interested in science, technology, psychology, philosophy, and linguistics."
	highlight = "solarized_dark"
	github = "https://github.com/vinayh"
	linkedin = "https://linkedin.com/in/vinayahiremath"
	facebook = "https://facebook.com/vinay427"
	twitter = "https://twitter.com/vinay427"
	gravatarHash = "e86ed2290d6849902585c105a69634e3"
